# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb713ff735e90530dfc887e4155049e1f6740e61d2c186cee421126ad9955550a19fc5112eb693eaeeb3e6a80164b09c0a0aeaefcbafbeb79d4bc6e450f78f7a

test:
  secret_key_base: 0ee96f4825ebc8a17f858379a3e088623011793a66246a37c8f6d7537c556001aa665524b51384d16aaed1e5b1b776436b8c09f78509d36ec811d3127a8b564d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
